# kneaddata
( /usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/hisat2_env/bin/kneaddata --input reads_1.fq.gz --input reads_2.fq.gz  --output ./hisat2_output/test/preprocessing --log ./hisat2_output/test/preprocessing/kneaddata.log --threads 4 --output-prefix kneaddata --bowtie2-options="--seed 0"  ) && ( /usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/hisat2_env/bin/repair.sh in1=./hisat2_output/test/preprocessing/kneaddata.trimmed.1.fastq in2=./hisat2_output/test/preprocessing/kneaddata.trimmed.2.fastq out1=./hisat2_output/test/preprocessing/kneaddata_repaired_1.fastq.gz out2=./hisat2_output/test/preprocessing/kneaddata_repaired_2.fastq.gz outs=./hisat2_output/test/preprocessing/kneaddata_repaired_singletons.fastq.gz overwrite=t ) && ( rm -f ./hisat2_output/test/preprocessing/kneaddata_paired* ./hisat2_output/test/preprocessing/*trimmed* )

# hisat2
rm -rf ./hisat2_output/test/tmp/* && ( /usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/hisat2_env/bin/hisat2 -x test.fa -1 ./hisat2_output/test/preprocessing/kneaddata_repaired_1.fastq.gz -2 ./hisat2_output/test/preprocessing/kneaddata_repaired_2.fastq.gz --threads 4 --un-conc-gz ./hisat2_output/test/intermediate/hisat2_output/unmapped_%.fastq.gz --seed 0  ) | ( /usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/hisat2_env/bin/samtools sort --threads 4 --reference test.fa -T ./hisat2_output/test/tmp/samtools_sort > ./hisat2_output/test/intermediate/hisat2_output/mapped.sorted.bam )

# featurecounts
(python /usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/hisat2_env/bin/fasta_to_saf.py -i test.fa > ./hisat2_output/test/intermediate/featurecounts_output/genome.saf ) && ( /usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/hisat2_env/bin/featureCounts -G test.fa -a ./hisat2_output/test/intermediate/featurecounts_output/genome.saf -o ./hisat2_output/test/intermediate/featurecounts_output/featurecounts.tsv -F SAF --tmpDir ./hisat2_output/test/tmp -T 4  ./hisat2_output/test/intermediate/hisat2_output/mapped.sorted.bam ) && gzip ./hisat2_output/test/intermediate/featurecounts_output/featurecounts.tsv

# symlink
( ln -f -s /local/ifs3_scratch/CORE/jespinoz/Oral/testing/hisat2_output/test/intermediate/hisat2_output/mapped.sorted.bam /local/ifs3_scratch/CORE/jespinoz/Oral/testing/hisat2_output/test/output && ln -f -s /local/ifs3_scratch/CORE/jespinoz/Oral/testing/hisat2_output/test/intermediate/featurecounts_output/featurecounts.tsv.gz /local/ifs3_scratch/CORE/jespinoz/Oral/testing/hisat2_output/test/output && ln -f -s /local/ifs3_scratch/CORE/jespinoz/Oral/testing/hisat2_output/test/intermediate/featurecounts_output/featurecounts.tsv.summary /local/ifs3_scratch/CORE/jespinoz/Oral/testing/hisat2_output/test/output )

